---


- name: Launch instance
  ec2:
     key_name: "{{ keypair }}"
     group: "{{security_groups}}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     wait: yes
     region: "{{ region }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: yes
     instance_tags:
        Name: test-webserver
     exact_count: "{{count}}"
     count_tag:
        Name: test-webserver
  register: ec2
- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances
- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
- name: Add the instances to known hosts
  local_action: command sh -c 'ssh-keyscan -t rsa {{ item.public_ip }} >> $HOME/.ssh/known_hosts'
  with_items: ec2.instances